//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public int ParticipantsID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal MonthlyRent { get; set; }
        public bool LegalEntity { get; set; }
        public bool IndividualEntrepreneur { get; set; }
    }
}
