//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Irina
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsTeams
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamMembers { get; set; }
    }
}
